# Generated by Django 4.2.11 on 2024-04-10 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_admin_alter_prettynum_level_alter_prettynum_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('content', models.TextField(verbose_name='Content')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.department', verbose_name='Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.employee', verbose_name='Employee')),
            ],
        ),
    ]
