# Generated by Django 4.2.11 on 2024-04-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='TIME'),
        ),
    ]
